name=ENES100
version=6.2.4
author=ENES100 Staff / John Paulenich
maintainer=John Paulenich
sentence=ENES100 Vision System library for Arduino boards.
paragraph=Uses native onboard WiFi on the Arduino UNO R4 WiFi and the external ENES100 WiFi module implementation on other compatible Arduino boards, including Uno, Mega, and Nano boards with SoftwareSerial support.
category=Communication
url=https://enes100.umd.edu/
architectures=*
includes=Enes100.h
